name: Publish to NuGet

on:
  push:
    branches:
      - main

jobs:
  publish:
    
    runs-on: ubuntu-latest
    environment:
      name: "Publish Release"
      
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore Dependencies
      run: dotnet restore src
    - name: Build
      run: dotnet build src --configuration Release --no-restore
    - name: Publish NuGet
      uses: alirezanet/publish-nuget@v3.1.0
      with:
        PROJECT_FILE_PATH: src/sharpbq.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}