name: .NET Build & Unit Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Check Out Code
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - name: Restore Dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Unit Tests
        run: |
          cd ./test/sharpbq.UnitTests/
          dotnet test --no-restore -nodereuse:false \
            /p:UseSharedCompilation=false \
            /p:UseRazorBuildServer=false \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=opencover \
            /p:CoverletOutput=/home/runner/work/sharpbq/ \
      - name: Publish Code Coverage
        uses: codecov/codecov-action@v4
        with:
          files: /home/runner/work/sharpbq/coverage.opencover.xml
          fail_ci_if_error: true